default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

<%=
  path = "#{Rails.root}/config/database_#{ENV['USER']}.yml"
  File.read(path) if File.exist?(path)
%>